name: 'End Colony Sandbox'
description: 'Ends a sandbox in Colony'
author: 'Quali'
inputs:
  space:
    description: 'Colony space'
    required: true
  sandbox_id:
    description: 'Colony Sandbox ID'
    required: true
  colony_token:
    description: 'Colony longterm token'
    required: true

runs:
  using: "composite"
  steps:
    - id: end-sandbox
      run: |
        sandbox=${{ inputs.sandbox_id }}
        echo "::debug::Ending sandbox $(echo "$sandbox")"
        python3 ${{ github.action_path }}/stop.py "$sandbox" "$timeout"
      shell: bash
