name: 'End Torque Sandbox'
description: 'Ends a Torque sandbox'
author: 'Quali'
inputs:
  space:
    description: 'The Torque space the sandbox is running in'
    required: true
  sandbox_id:
    description: 'The Torque Sandbox ID to end'
    required: true
  torque_token:
    description: 'A Torque longterm token'
    required: true
  torque_hostname:
    description: 'Alternative Torque server url'
    required: false
    default: portal.qtorque.io
    
runs:
  using: "docker"
  image: "ddovbii/torque-cli"
  args:
    - sb
    - end
    - ${{ inputs.sandbox_id }}

  env:
    TORQUE_TOKEN: ${{ inputs.torque_token }}
    TORQUE_SPACE: ${{ inputs.space }}
    TORQUE_HOSTNAME: ${{ inputs.torque_hostname }}

branding:
  icon: 'stop-circle'  
  color: 'red'
