name: 'End Colony Sandbox'
description: 'Ends a CloudShell Colony sandbox'
author: 'Quali'
inputs:
  space:
    description: 'The Colony space the sandbox is running in'
    required: true
  sandbox_id:
    description: 'The Colony Sandbox ID to end'
    required: true
  colony_token:
    description: 'A Colony longterm token'
    required: true

runs:
  using: "composite"
  steps:
    - id: end-sandbox
      run: |
        sandbox=${{ inputs.sandbox_id }}
        echo "::debug::Ending sandbox $(echo $sandbox)"
        python3 ${{ github.action_path }}/stop.py "$sandbox"
      shell: bash
      env:
        COLONY_SPACE: ${{ inputs.space }}
        COLONY_TOKEN: ${{ inputs.colony_token }}
    
branding:
  icon: 'stop-circle'  
  color: 'red'
