name: 'End Torque Sandbox'
description: 'Ends a Torque sandbox'
author: 'Quali'
inputs:
  space:
    description: 'The Torque space the sandbox is running in'
    required: true
  sandbox_id:
    description: 'The Torque Sandbox ID to end'
    required: true
  torque_token:
    description: 'A Torque longterm token'
    required: true
  torque_url:
    description: 'Alternative Torque server url'
    required: false
    default: https://portal.qtorque.io
    
runs:
  using: "composite"
  steps:
    - id: end-sandbox
      run: |
        sandbox=${{ inputs.sandbox_id }}
        echo "::debug::Ending sandbox $(echo $sandbox)"
        python3 ${{ github.action_path }}/stop.py "$sandbox"
      shell: bash
      env:
        TORQUE_SPACE: ${{ inputs.space }}
        TORQUE_TOKEN: ${{ inputs.torque_token }}
        TORQUE_URL: ${{ inputs.torque_url }}
    
branding:
  icon: 'stop-circle'  
  color: 'red'
